export const dom = {
  amountInput: document.getElementById('amount'),
  fromCurrency: document.getElementById('from-currency'),
  toCurrency: document.getElementById('to-currency'),
  resultValue: document.getElementById('result-value'),
  resultMeta: document.getElementById('result-meta'),
  convertCurrencyBtn: document.getElementById('convert-currency-btn'),
  converterForm: document.getElementById('converter-form'),
  swapBtn: document.getElementById('swap-btn'),
  stockWatchList: document.getElementById('stock-watchlist'),
  stockSymbolInput: document.getElementById('stock-symbol'),
  stockForm: document.getElementById('stock-form'),
  cancelConfirmationBtn: document.getElementById('cancel-confirmation-btn'),
  confirmActionBtn: document.getElementById('confirm-action-btn'),
  confirmationModal: document.getElementById('confirmation-modal'),
  confirmationTitle: document.getElementById('confirmation-title'),
  confirmationMessage: document.getElementById('confirmation-message'),
  clearStocksBtn: document.getElementById('clear-stocks-btn'),
  refreshStocksBtn: document.getElementById('refresh-stocks-btn'),
  toastContainer: document.getElementById('toast-container'),
  stockSearchResults: document.getElementById('stock-search-results'),
  metalsList: document.getElementById('metals-list'),
  refreshMetalsBtn: document.getElementById('refresh-metals-btn'),
  stocksUpdatedMeta: document.getElementById('stocks-updated-meta'),
  metalsUpdatedMeta: document.getElementById('metals-updated-meta'),
};
