export const dom = {
  form: document.getElementById('new-transaction-form'),
  overlay: document.getElementById('transaction-form-overlay'),
  transactionFormTitle: document.getElementById('transaction-form-title'),
  transactionDate: document.getElementById('transaction-date'),
  transactionCategory: document.getElementById('transaction-category'),
  transactionDescription: document.getElementById('transaction-description'),
  transactionAmount: document.getElementById('transaction-amount'),
  formMessage: document.getElementById('form-message'),
  typeInputs: document.querySelectorAll('input[name="transaction-type"]'),
  statusInputs: document.querySelectorAll('input[name="transaction-status"]'),
  pendingStatusInput: document.querySelector('input[name="transaction-status"][value="pending"]'),
  postedStatusInput: document.querySelector('input[name="transaction-status"][value="posted"]'),
  submitBtn: document.getElementById('submit-btn'),
  cancelBtn: document.getElementById('cancel-btn'),
  deleteBtn: document.getElementById('delete-btn'),
  closeBtn: document.getElementById('close-transaction-form-btn'),
  newBtn: document.getElementById('new-transaction-btn'),
  clearLedgerBtn: document.getElementById('clear-ledger-btn'),
  exportLedgerBtn: document.getElementById('export-ledger-btn'),
  importLedgerInput: document.getElementById('import-ledger-input'),

  transactionCount: document.getElementById('transaction-count'),
  pendingCount: document.getElementById('pending-count'),
  postedBalance: document.getElementById('posted-balance'),
  projectedBalance: document.getElementById('projected-balance'),

  pendingLedgerHeader: document.getElementById('pending-ledger-header'),
  pendingTransactions: document.getElementById('pending-transactions'),
  postedLedgerHeader: document.getElementById('posted-ledger-header'),
  postedTransactions: document.getElementById('posted-transactions'),

  deleteConfirmMessage: document.getElementById('delete-confirm-message'),
  deleteConfirmOverlay: document.getElementById('delete-confirm-overlay'),
  confirmDeleteBtn: document.getElementById('confirm-delete-btn'),
  cancelDeleteBtn: document.getElementById('cancel-delete-btn'),

  toastContainer: document.getElementById('toast-container'),

  discardConfirmOverlay: document.getElementById('discard-confirm-overlay'),
  keepEditingBtn: document.getElementById('keep-editing-btn'),
  discardChangesBtn: document.getElementById('discard-changes-btn'),
  discardReviewContents: document.getElementById('discard-review-contents'),

  overdraftConfirmOverlay: document.getElementById('overdraft-confirm-overlay'),
  overdraftModalTitle: document.getElementById('overdraft-modal-title'),
  overdraftConfirmMessage: document.getElementById('overdraft-confirm-message'),
  overdraftContextDate: document.getElementById('overdraft-context-date'),
  overdraftContextDescription: document.getElementById('overdraft-context-description'),
  overdraftReviewContents: document.getElementById('overdraft-review-contents'),
  overdraftProceedBtn: document.getElementById('overdraft-proceed-btn'),
  overdraftEditBtn: document.getElementById('overdraft-edit-btn'),
  overdraftCancelBtn: document.getElementById('overdraft-cancel-btn'),

  importLedgerOverlay: document.getElementById('import-ledger-overlay'),
  importLedgerSummary: document.getElementById('import-ledger-summary'),
  confirmImportLedgerBtn: document.getElementById('confirm-import-ledger-btn'),
  cancelImportLedgerBtn: document.getElementById('cancel-import-ledger-btn'),

  clearLedgerOverlay: document.getElementById('clear-ledger-overlay'),
  clearLedgerSummary: document.getElementById('clear-ledger-summary'),
  confirmClearLedgerBtn: document.getElementById('confirm-clear-ledger-btn'),
  cancelClearLedgerBtn: document.getElementById('cancel-clear-ledger-btn'),
};
